---

- hosts: all
  gather_facts: yes
  become: false
  
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_kernel }}"
    - "{{ ansible_architecture }}"
    - "{{ ansible_lsb }}"