---
- name: System information
  hosts: all
  gather_facts: true
  become: false

  tasks:
    - name: System details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ansible_kernel }}"
        - "{{ ansible_architecture }}"
        - "{{ ansible_lsb }}"
